### ISSUE TITLE
Add tests for when the data doesn´t have a name

### ISSUE THREAD

**Issue by jlopezper** [rOpenSpain/opendataes#12]
When reading a file from Madrid, we encountered a problem with files that didn´t have names in datos.gob.es. For example, this one: http://datos.gob.es/es/catalogo/l01280796-sedes-oficinas-de-elaboracion-de-dni-y-pasaporte1

We fixed this but we need to add a test that when it reads THIS datasets, it makes sure that the name is "Distribucion sin nombre".

**Comment by cimentadaj** [comment]
This is already implemented in the test section of `cargar_datos` but commented out because it does done with a dataset from Madrid, a publisher not yet available. Comment out this test once Madrid is accepted in `publishers_available`.
