### ISSUE TITLE
Improve the API

### ISSUE THREAD

**Issue by Enchufa2** [rOpenSpain/opendataes#13]
## English API

Right now, there are some functions in English, some functions (and file names) in Spanish (`cargar_datos`) and some of them in _Spanglish_, such as `explorar_keywords` or `cargar_publishers`. If we want the package to be reusable by a broad audience, everything should be in English.

## Easy-to-use API

There is some open discussion on whether prefixed functions are a good or a bad thing. I don't specially like this in general, but I agree that this is very useful for those packages aimed at accessing an API, such as this one. As the [rOpenSci guidelines](https://ropensci.github.io/dev_guide/building.html#package-api) state, for this particular use case, this makes code more readable and easy to auto-complete.

So I'd propose a common prefix for those exported functions that directly interact with the API. For instance, instead of `explore_keywords`, `dges_explore_keywords` (_dges_ after **d**atos.**g**ob.**es**; but I don't particularly care about the specific prefix chosen).

**Comment by jlopezper** [comment]
Thanks for opening this issue @Enchufa2!

Regarding the two points you mention:
1) English API: it was a discussion that @cimentadaj and I had in the very beginning days. In the end we decided to keep the main functions in Spanish because the package accesses to data from Spanish institutions and being aware that the documentation is entirely provided in English. Honestly, I can't find a stronger reason to keep them as they are.
2) Easy-to-use API: I'm fully agree with this.

What's your view @cimentadaj?

**Comment by Enchufa2** [comment]
The documentation is provided in English, yes, but I rarely (i.e., never) start by reading the whole documentation. Instead, I type something, hit tab, and then I am guided by function names. Think about a package for accessing German data with functions names in German... ;-)

**Comment by cimentadaj** [comment]
Hi @Enchufa2, thanks for geting involved in the project! Your concerns are very valid. I think @jlopezper 
 and me agree that function names could be improved. The most generic names would be something along the lines of `load_data` and `explore_keywords`. But of course, these are **too** generic. A simple google search already shows a function called `load_data` in `devtools` that could create conflicts.

I'm not entirely against the prefix practice but I wouldn't want the function names to be long. The prefix would be a good idea as long as intuitively related to the package name (for example `use_` in `usethis`). I think combining `dges_` with the function names is too long and not straight forward. Ideally, there should be some verb in the name to denote what it does.

I suggest to cut the names altogether and just choose a shorter prefix. I have no idea which should be the prefix, but let's brainstorm.

`dge_data`, `dge_keywords`
`opnes_load_data`, `opnes_load_keywords` # too long
`openspain_data`, `openspain_keywords`
`openes_data`, `openes_keywords`
`openes_download`, `openes_search`

@jlopezper @Enchufa2, feel free to combine, criticize or add new options. I wouldn't mind dropping the `cargar_` for a shorter prefix and I think it would still be obvious that it's to load data.

**Comment by Enchufa2** [comment]
Thanks for considering this. If there's no package using just `od_` already, I think it's a good prefix.

**Comment by jlopezper** [comment]
Just for being more intuitive, I'd prefer the prefix `openes_*` than `dge_*` although this will force us to choose short names. For the current main functions I propose `openes_load` and `openes_explore`.

**Comment by jlopezper** [comment]
In the end, we've decided to set the following names: `openes_load`, `openes_keywords` and `openes_publishers`. Thanks @Enchufa2 for pointing this out.
