### ISSUE TITLE
Publishers Available Error Message

### ISSUE THREAD

**Issue by ajcanepa** [rOpenSpain/opendataes#23]
When I tried to open a vaccination dataset (see [here](https://datos.gob.es/es/catalogo/a07002862-vacunacion-covid-19-por-grupo-y-criterio)) from the __Junta de Castilla y León__, I got the following Error Message:
`Error in openes_load.character("a07002862-vacunacion-covid-19-por-grupo-y-criterio") : 
  Publisher not available. Please check publishers_available() to get the available ones.`

And when Iexecute `publishers_available()`, the following Error Message appears: 
`Error in publishers_available() : 
  could not find function "publishers_available"`

The thing is:
*    1) The function to pick-up all the available publishers seems to be, or at least that worked for me:
`publishers_available$publishers`.
*    2) I can see that *Junta de Castilla y León* isn't listed, How Can I add a new Publisher?

Thanks!

**Comment by jlopezper** [comment]
The error message is not correct. It is true that this publisher is not available, but `publishers_available` is a `data.frame`, not a `function`. I'll try to fix that as soon as possible.

```
r$> publishers_available                                              
# A tibble: 10 x 2
   publishers                                 publisher_code
   <chr>                                      <chr>         
 1 Ayuntamiento de Barcelona                  L01080193     
 2 Ayuntamiento de Madrid                     L01280796     
 3 Ayuntamiento de Valencia                   L01462508     
 4 Ayuntamiento de Las Palmas de Gran Canaria L01350167     
 5 Ayuntamiento de Bilbao                     L01480209     
 6 Ayuntamiento de Zaragoza                   L01502973     
 7 Ayuntamiento de Malaga                     L01290672     
 8 Ayuntamiento de Gijon                      L01330241     
 9 Ayuntamiento de Santander                  L01390759     
10 Ayuntamiento de Alcobendas                 L01280066   
```

On the other hand, before introducing a new publisher we like to run some tests to make sure we're able to guarantee the quality. I'm going to work to include this publisher and will let you know once it's done.

**Comment by ajcanepa** [comment]
Many thanks in advance!
I was aware of the difference between the `function` and the `data.frame`, but probably I explained myself wrongly.
I don't know if the data in datos.gob.es is the same as the data inside the JCyL open data portal (see [here](https://datosabiertos.jcyl.es/web/es/datos-abiertos-castilla-leon.html)), any case if I can collaborate in some way, just let me know.

Thanks again!

**Comment by ajcanepa** [comment]
> The error message is not correct. It is true that this publisher is not available, but `publishers_available` is a `data.frame`, not a `function`. I'll try to fix that as soon as possible.
> 
> ```
> r$> publishers_available                                              
> # A tibble: 10 x 2
>    publishers                                 publisher_code
>    <chr>                                      <chr>         
>  1 Ayuntamiento de Barcelona                  L01080193     
>  2 Ayuntamiento de Madrid                     L01280796     
>  3 Ayuntamiento de Valencia                   L01462508     
>  4 Ayuntamiento de Las Palmas de Gran Canaria L01350167     
>  5 Ayuntamiento de Bilbao                     L01480209     
>  6 Ayuntamiento de Zaragoza                   L01502973     
>  7 Ayuntamiento de Malaga                     L01290672     
>  8 Ayuntamiento de Gijon                      L01330241     
>  9 Ayuntamiento de Santander                  L01390759     
> 10 Ayuntamiento de Alcobendas                 L01280066   
> ```
> 
> On the other hand, before introducing a new publisher we like to run some tests to make sure we're able to guarantee the quality. I'm going to work to include this publisher and will let you know once it's done.

HI @jlopezper , Do you have some news about the CyL publisher? I'm trying to include these available datasets (or those found [here](https://datosabiertos.jcyl.es/web/es/datos-abiertos-castilla-leon.html)) into my Classes at the University and even they do not have a very good quality, they will have a "demonstrative" value; since will be very nice to access them.  

Many thanks in advance!

**Comment by jlopezper** [comment]
Junta CyL is already available, @ajcanepa. Please download the latest version of the package.

Sorry for the delay!
